version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-together-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fv9ot1669nzf"
s3_prefix = "todo-together-api"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
