AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 15
    Handler: app.handler
    Runtime: python3.8
    Layers:
    - !GetAtt BaseLayer.Arn
    Environment:
      Variables:
        API_VERSION: 1.0
        JWT_ALGORITHM: HS256
        USER_TABLE: TodoTogetherUsers
        LIST_TABLE: TodoTogetherLists
        JWT_SECRET_NAME: TodoTogetherJwtSecret
        TOKEN_EXPIRY_MINS: 60
    Tags:
    - Key: project
      Value: todo-together

Resources:
  TodoAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: TodoTogetherAPI
      StageName: prod
      Tags:
      - Key: project
        Value: todo-together

  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: user_id
        Type: String
      TableName: TodoTogetherUsers
      Tags:
      - Key: project
        Value: todo-together

  ListTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: list_id
        Type: String
      TableName: TodoTogetherLists
      Tags:
      - Key: project
        Value: todo-together

  BaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./base-layer/
      LayerName: TodoBaseLayer
      CompatibleRuntimes:
      - python3.8
      RetentionPolicy: Retain
      Tags:
      - Key: project
        Value: todo-together

  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/users/index/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref TodoAPI

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/auth/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /auth
            Method: post
            RestApiId: !Ref TodoAPI

  ListUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/users/index/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /users
            Method: get
            RestApiId: !Ref TodoAPI

  NewUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/users/new/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /users/new
            Method: get
            RestApiId: !Ref TodoAPI

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/users/user/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /users/{user_id}
            Method: get
            RestApiId: !Ref TodoAPI

  ListListsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/lists/index/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /lists
            Method: get
            RestApiId: !Ref TodoAPI

  NewListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/lists/new/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /lists/new
            Method: get
            RestApiId: !Ref TodoAPI

  GetListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/lists/list/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /lists/{list_id}
            Method: get
            RestApiId: !Ref TodoAPI

  LogEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/event/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /event
            Method: get
            RestApiId: !Ref TodoAPI


Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${TodoAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/"
