AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 3
    PackageType: Image
    Environment:
      Variables:
        API_VERSION: 1.0.0
    Tags:
    - Key: project
      Value: todo-together

Resources:
  TodoAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: TodoTogetherAPI
      StageName: prod
      Tags:
      - Key: project
        Value: todo-together

  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: UserID
        Type: String
      TableName: TodoTogetherUsers
      Tags:
      - Key: project
        Value: todo-together

  ListTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ListID
        Type: String
      TableName: TodoTogetherLists
      Tags:
      - Key: project
        Value: todo-together

  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda-functions/index
      DockerTag: python3.8-v1

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
