AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 15
    Handler: app.lambda_handler
    Runtime: python3.8
    Layers:
      - !Ref BaseLayer
    Environment:
      Variables:
        API_VERSION: 1.0
        JWT_ALGORITHM: HS256
        TOKEN_EXPIRY_MINS: 60
        JWT_SECRET_NAME: TodoTogetherJwtSecret
        USER_TABLE: TodoTogetherUsers
        LIST_TABLE: TodoTogetherLists

Resources:
  TodoAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: TodoTogetherAPI
      StageName: prod
      Cors:
        AllowMethods: "'POST, GET, DELETE, OPTIONS'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "*"
        MaxAge: "'600'"
        AllowCredentials: true


  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: user_id
        Type: String
      TableName: TodoTogetherUsers

  ListTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: list_id
        Type: String
      TableName: TodoTogetherLists

  BaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./base-layer/
      LayerName: TodoBaseLayer
      CompatibleRuntimes:
      - python3.8

  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/index/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref TodoAPI

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/auth/
      Policies:
        - DynamoDBReadPolicy:
            TableName: TodoTogetherUsers
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:580367176505:secret:TodoTogetherJwtSecret-vA5hHU"

      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /auth
            Method: post
            RestApiId: !Ref TodoAPI

  ListUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/users/index/
      Policies:
        - DynamoDBReadPolicy:
            TableName: TodoTogetherUsers
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:580367176505:secret:TodoTogetherJwtSecret-vA5hHU"
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /users
            Method: get
            RestApiId: !Ref TodoAPI

  NewUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/users/new/
      Policies:
        DynamoDBCrudPolicy:
          TableName: TodoTogetherUsers          
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /users/new
            Method: post
            RestApiId: !Ref TodoAPI


  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/users/user/
      Policies:
        - DynamoDBReadPolicy:
            TableName: TodoTogetherUsers
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:580367176505:secret:TodoTogetherJwtSecret-vA5hHU"
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /users/{user_id}
            Method: get
            RestApiId: !Ref TodoAPI

  ListListsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/lists/index/
      Policies:
        - DynamoDBReadPolicy:
            TableName: TodoTogetherUsers
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:580367176505:secret:TodoTogetherJwtSecret-vA5hHU"
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /lists
            Method: get
            RestApiId: !Ref TodoAPI

  NewListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/lists/new/
      Policies:
        - DynamoDBReadPolicy:
            TableName: TodoTogetherUsers
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:580367176505:secret:TodoTogetherJwtSecret-vA5hHU"
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /lists/new
            Method: get
            RestApiId: !Ref TodoAPI

  GetListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/lists/list/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /lists/{list_id}
            Method: get
            RestApiId: !Ref TodoAPI

  LogEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/event/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /event
            Method: get
            RestApiId: !Ref TodoAPI


Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${TodoAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/"
